export const hobbiesList = [
    { value: 'Archery', label: 'Archery' },
    { value: 'Astronomy', label: 'Astronomy' },
    { value: 'Attending concerts', label: 'Attending concerts' },
    { value: 'Baking', label: 'Baking' },
    { value: 'Basketball', label: 'Basketball' },
    { value: 'Beekeeping', label: 'Beekeeping' },
    { value: 'Birdwatching', label: 'Birdwatching' },
    { value: 'Board games', label: 'Board games' },
    { value: 'Brewing beer', label: 'Brewing beer' },
    { value: 'Collecting', label: 'Collecting' },
    { value: 'Cooking', label: 'Cooking' },
    { value: 'Cycling', label: 'Cycling' },
    { value: 'Dancing', label: 'Dancing' },
    { value: 'DIY projects', label: 'DIY projects' },
    { value: 'Drawing', label: 'Drawing' },
    { value: 'Fishing', label: 'Fishing' },
    { value: 'Film photography', label: 'Film photography' },
    { value: 'Football', label: 'Football' },
    { value: 'Gardening', label: 'Gardening' },
    { value: 'Hiking', label: 'Hiking' },
    { value: 'Home improvement', label: 'Home improvement' },
    { value: 'Horseback riding', label: 'Horseback riding' },
    { value: 'Karaoke', label: 'Karaoke' },
    { value: 'Learning languages', label: 'Learning languages' },
    { value: 'Listening to music', label: 'Listening to music' },
    { value: 'Music appreciation', label: 'Music appreciation' },
    { value: 'Paintball', label: 'Paintball' },
    { value: 'Painting', label: 'Painting' },
    { value: 'Photography', label: 'Photography' },
    { value: 'Playing musical instruments', label: 'Playing musical instruments' },
    { value: 'Playing sports', label: 'Playing sports' },
    { value: 'Playing video games', label: 'Playing video games' },
    { value: 'Pottery', label: 'Pottery' },
    { value: 'Reading', label: 'Reading' },
    { value: 'Reading comics', label: 'Reading comics' },
    { value: 'Rock climbing', label: 'Rock climbing' },
    { value: 'Running', label: 'Running' },
    { value: 'Scuba diving', label: 'Scuba diving' },
    { value: 'Sculpting', label: 'Sculpting' },
    { value: 'Skiing', label: 'Skiing' },
    { value: 'Surfing', label: 'Surfing' },
    { value: 'Surfing the internet', label: 'Surfing the internet' },
    { value: 'Traveling', label: 'Traveling' },
    { value: 'Volunteering', label: 'Volunteering' },
    { value: 'Watching movies', label: 'Watching movies' },
    { value: 'Wine making', label: 'Wine making' },
    { value: 'Wine tasting', label: 'Wine tasting' },
    { value: 'Woodworking', label: 'Woodworking' },
    { value: 'Writing', label: 'Writing' },
    { value: 'Writing fiction', label: 'Writing fiction' },
    { value: 'Writing poetry', label: 'Writing poetry' },
    { value: 'Yoga', label: 'Yoga' }
  ];

  export const preferencesList = [
    { value: 'Accessibility features', label: 'Accessibility features' },
    { value: 'Cleanliness and tidiness', label: 'Cleanliness and tidiness' },
    { value: 'Close amenities', label: 'Close amenities' },
    { value: 'Cultural venue access', label: 'Cultural venue access' },
    { value: 'Decor style preference', label: 'Decor style preference' },
    { value: 'Dietary requirements', label: 'Dietary requirements' },
    { value: 'Flexible schedules', label: 'Flexible schedules' },
    { value: 'Fitness amenities', label: 'Fitness amenities' },
    { value: 'Furnished living space', label: 'Furnished living space' },
    { value: 'Gardening opportunities', label: 'Gardening opportunities' },
    { value: 'Green living initiatives', label: 'Green living initiatives' },
    { value: 'Hosting pets', label: 'Hosting pets' },
    { value: 'Natural lighting preference', label: 'Natural lighting preference' },
    { value: 'Non-smoking environment', label: 'Non-smoking environment' },
    { value: 'Organized living environment', label: 'Organized living environment' },
    { value: 'Outdoor access', label: 'Outdoor access' },
    { value: 'Pet-friendly environment', label: 'Pet-friendly environment' },
    { value: 'Privacy and space', label: 'Privacy and space' },
    { value: 'Private bathroom', label: 'Private bathroom' },
    { value: 'Quiet hours', label: 'Quiet hours' },
    { value: 'Quiet hours preference', label: 'Quiet hours preference' },
    { value: 'Quiet living space', label: 'Quiet living space' },
    { value: 'Recreational activities proximity', label: 'Recreational activities proximity' },
    { value: 'Security features', label: 'Security features' },
    { value: 'Separate kitchen', label: 'Separate kitchen' },
    { value: 'Shared cooking responsibilities', label: 'Shared cooking responsibilities' },
    { value: 'Shared interests/hobbies', label: 'Shared interests/hobbies' },
    { value: 'Shared responsibilities', label: 'Shared responsibilities' },
    { value: 'Shared storage space', label: 'Shared storage space' },
    { value: 'Shared workspace', label: 'Shared workspace' },
    { value: 'Socializing preferences', label: 'Socializing preferences' },
    { value: 'Spacious bedroom', label: 'Spacious bedroom' },
    { value: 'Special dietary requirements', label: 'Special dietary requirements' },
    { value: 'Sustainability practices', label: 'Sustainability practices' },
    { value: 'Temperature control', label: 'Temperature control' },
    { value: 'Visitor policy', label: 'Visitor policy' },
    { value: 'Workspace availability', label: 'Workspace availability' },
    { value: 'Laundry facilities availability', label: 'Laundry facilities availability' }
    // Add more preferences as needed
  ];
  


export const types  = [
    {value:"Intern", label:"Intern"},
    {value:"Employee", label:"Employee"},
    {value:"Consultant", label:"Consultant"},
];

export const periods  = [
    {value:"Short", label:"Short"},
    {value:"Medium", label:"Medium"},
    {value:"Long", label:"Long"},
];

