// MADE UP BY CHATGPT

const mockListings = [
  {
    id: 0,
    title: "Luxury London Flat",
    description:
      "Spacious and luxurious flat with breathtaking views of the London skyline, located in the heart of the city.",
    price: 2000,
    propertyType: "Flat",
    ownerType: "External Provider",
    city: "London",
    address:
      "Flat 21, The Vision Building, 15 Argyle Street, Camden, London, WC1H 8EJ",
    nearbyStations: [
      "King's Cross St Pancras",
      "Euston",
      "Mornington Crescent",
    ],
    bedrooms: 2,
    bathrooms: 2,
    area: "900 sqft",
    images: [
      "/images/0_0.jpg",
      "/images/0_1.jpg",
      "/images/0_2.jpg",
      "/images/0_3.jpg",
      "/images/0_4.jpg",
      "/images/0_5.jpg",
      "/images/0_6.jpg",
    ],
    IMAGES_FROM:
      "https://www.spareroom.co.uk/flatshare/flatshare_detail.pl?flatshare_id=3678912&search_id=1285309264&city_id=9&flatshare_type=offered&search_results=%2Fflatshare%2F%3Fsearch_id%3D1285309264%26&",
  },
  {
    id: 1,
    title: "Charming Flat in Notting Hill",
    description:
      "Quaint flat with a rustic charm, featuring hardwood floors and a fireplace, perfect for cozy evenings.",
    price: 1500,
    propertyType: "Flat",
    ownerType: "Internal Employee",
    city: "London",
    address: "33 Westbourne Grove, London W2 4UA, UK",
    nearbyStations: ["Notting Hill Gate", "Bayswater"],
    bedrooms: 1,
    bathrooms: 1,
    area: "700 sqft",
    images: [
      "/images/1_0.jpg",
      "/images/1_1.jpg",
      "/images/1_2.jpg",
      "/images/1_3.jpg",
      "/images/1_4.jpg",
      "/images/1_5.jpg",
      "/images/1_6.jpg",
    ],
    IMAGES_FROM:
      "https://www.spareroom.co.uk/flatshare/flatshare_detail.pl?flatshare_id=17187895&search_id=1285310783&city_id=&flatshare_type=offered&search_results=%2Fflatshare%2F%3Fsearch_id%3D1285310783%26&",
  },
  {
    id: 2,
    title: "Modern Shared Room in Camden",
    description:
      "Join a vibrant flatshare in an up-and-coming area, with each room sporting a unique artistic design.",
    price: 800,
    propertyType: "Shared Room",
    ownerType: "External Provider",
    city: "London",
    address: "15 Camden High St, London NW1 7JE, UK",
    nearbyStations: ["Camden Town", "Mornington Crescent"],
    bedrooms: 1,
    bathrooms: 2,
    area: "500 sqft",
    images: [
      "/images/2_0.jpg",
      "/images/2_1.jpg",
      "/images/2_2.jpg",
      "/images/2_3.jpg",
      "/images/2_4.jpg",
      "/images/2_5.jpg",
      "/images/2_6.jpg",
      "/images/2_7.jpg",
    ],
    IMAGES_FROM:
      "https://www.spareroom.co.uk/flatshare/flatshare_detail.pl?flatshare_id=16580808&search_id=1285312224&city_id=9&flatshare_type=offered&search_results=%2Fflatshare%2F%3Fsearch_id%3D1285312224&",
  },
  {
    id: 3,
    title: "Detached House in Manchester",
    description:
      "Spacious family home in a quiet neighbourhood, with a large garden and driveway parking.",
    price: 2000,
    propertyType: "House",
    ownerType: "External Provider",
    city: "Manchester",
    address: "42 Didsbury Park, Manchester M20 5LH, UK",
    nearbyStations: ["East Didsbury", "Burnage"],
    bedrooms: 3,
    bathrooms: 2,
    area: "1200 sqft",
    images: [
      "/images/3_0.jpg",
      "/images/3_1.jpg",
      "/images/3_2.jpg",
      "/images/3_3.jpg",
      "/images/3_4.jpg",
      "/images/3_5.jpg",
      "/images/3_6.jpg",
      "/images/3_7.jpg",
      "/images/3_8.jpg",
    ],
    IMAGES_FROM:
      "https://www.spareroom.co.uk/flatshare/flatshare_detail.pl?flatshare_id=15977661&search_id=1285312893&city_id=&flatshare_type=offered&search_results=%2Fflatshare%2F%3Fsearch_id%3D1285312893&",
  },
  {
    id: 4,
    title: "Stylish Flat in Leeds",
    description:
      "Urban loft with high ceilings and large windows offering panoramic views of the city.",
    price: 1100,
    propertyType: "Flat",
    ownerType: "Internal Employee",
    city: "Leeds",
    address: "88 Headrow, Leeds LS1 8EQ, UK",
    nearbyStations: ["Leeds Station"],
    bedrooms: 2,
    bathrooms: 1,
    area: "800 sqft",
    images: [
      "/images/4_0.jpg",
      "/images/4_1.jpg",
      "/images/4_2.jpg",
      "/images/4_3.jpg",
      "/images/4_4.jpg",
      "/images/4_5.jpg",
      "/images/4_6.jpg",
      "/images/4_7.jpg",
    ],
    IMAGES_FROM:
      "https://www.spareroom.co.uk/flatshare/flatshare_detail.pl?flatshare_id=17199545&search_id=1285315296&city_id=&flatshare_type=offered&search_results=%2Fflatshare%2F%3Fsearch_id%3D1285315296&",
  },
  {
    id: 5,
    title: "Luxurious penthouse in Edinburgh",
    description:
      "Fully renovated townhouse with period features and a modern kitchen, situated in the heart of the city.",
    price: 1800,
    propertyType: "Flat",
    ownerType: "External Provider",
    city: "Edinburgh",
    address: "17 Royal Terrace, Edinburgh EH7 5AB, UK",
    nearbyStations: ["Edinburgh Waverley"],
    bedrooms: 2,
    bathrooms: 2,
    area: "950 sqft",
    images: [
      "/images/5_0.jpg",
      "/images/5_1.jpg",
      "/images/5_2.jpg",
      "/images/5_3.jpg",
      "/images/5_4.jpg",
      "/images/5_5.jpg",
      "/images/5_6.jpg",
      "/images/5_7.jpg",
    ],
    IMAGES_FROM:
      "https://www.spareroom.co.uk/flatshare/flatshare_detail.pl?flatshare_id=16427645&search_id=1285316006&city_id=&flatshare_type=offered&search_results=%2Fflatshare%2F%3Foffset%3D10%26search_id%3D1285316006%26sort_by%3Dby_day%26mode%3Dlist&",
  },
  {
    id: 6,
    title: "Contemporary Studio in Birmingham",
    description:
      "Compact and efficient studio with cutting-edge technology and a sleek design, perfect for young professionals.",
    price: 1500,
    propertyType: "Studio",
    ownerType: "Internal Employee",
    address: "5 New St, Birmingham B2 4RQ, UK",
    city: "Birmingham",
    nearbyStations: ["Birmingham New Street", "Birmingham Moor Street"],
    bedrooms: 1,
    bathrooms: 1,
    area: "450 sqft",
    images: [
      "/images/6_0.jpg",
      "/images/6_1.jpg",
      "/images/6_2.jpg",
      "/images/6_3.jpg",
      "/images/6_4.jpg",
      "/images/6_5.jpg",
      "/images/6_6.jpg",
    ],
    IMAGES_FROM:
      "https://www.spareroom.co.uk/flatshare/flatshare_detail.pl?flatshare_id=16558437&search_id=1285316631&city_id=&flatshare_type=offered&search_results=%2Fflatshare%2F%3Fsearch_id%3D1285316631&",
  },

  {
    id: 7,
    title: "Luxury Apartment in New York City",
    description:
      "Exquisite apartment located in the heart of Manhattan, offering stunning views of the city skyline and luxurious amenities.",
    price: 4000,
    propertyType: "Apartment",
    ownerType: "Internal Employee",
    city: "New York City",
    address: "123 Broadway, New York, NY 10001, USA",
    nearbyStations: ["Times Square", "Penn Station"],
    bedrooms: 3,
    bathrooms: 2,
    area: "2000 sqft",
    images: [
      "/images/7_0.jpg",
      "/images/7_1.jpg",
      "/images/7_2.jpg",
      "/images/7_3.jpg",
      "/images/7_4.jpg",
      "/images/7_5.jpg",
      "/images/7_6.jpg",
    ],
    IMAGES_FROM:
      "https://thehazeljc.com/?utm_source=Google_Ads&utm_medium=Search&utm_term=Luxury%20Apartments%20Near%20Nyc&gad_source=1&gclid=CjwKCAjwte-vBhBFEiwAQSv_xSIbS1qUH8BI0w_zOKL_YDutnDkYrUZbCD6z3yWlSplEK6i9DE5rQhoCpJYQAvD_BwE",
  },
  {
    id: 8,
    title: "Downtown Condo in Toronto",
    description:
      "Modern condo located in downtown Toronto, offering convenient access to shops, restaurants, and entertainment.",
    price: 1000,
    propertyType: "Condo",
    ownerType: "Internal Employee",
    city: "Toronto",
    address: "123 King St W, Toronto, ON M5H 3M8, Canada",
    nearbyStations: ["Union Station", "St. Andrew"],
    bedrooms: 2,
    bathrooms: 2,
    area: "1500 sqft",
    images: [
      "/images/8_0.jpg",
      "/images/8_1.jpg",
      "/images/8_2.jpg",
      "/images/8_3.jpg",
      "/images/8_4.jpg",
      "/images/8_5.jpg",
      "/images/8_6.jpg",
    ],
    IMAGES_FROM:
      "https://www.booking.com/hotel/ca/trendy-downtown-toronto-condo.en-gb.html?aid=318615&label=New_English_EN_ES_21457893385-TTKU5WNpzZlV3nreO8zMBgS640819029771%3Apl%3Ata%3Ap1%3Ap2%3Aac%3Aap%3Aneg&sid=461f62bc885b914bcd5e172a1142b6f7&dest_id=-574890&dest_type=city&dist=0&group_adults=2&group_children=0&hapos=1&hpos=1&no_rooms=1&req_adults=2&req_children=0&room1=A%2CA&sb_price_type=total&sr_order=popularity&srepoch=1711060206&srpvid=68059e3127140058&type=total&ucfs=1&activeTab=main",
  },
  {
    id: 9,
    title: "Modern Apartment in Reston",
    description:
      "Sleek apartment located in Reston, offering contemporary living spaces and access to nearby parks and recreational facilities.",
    price: 1500,
    propertyType: "Apartment",
    ownerType: "Internal Employee",
    city: "Reston",
    address: "123 Market St, Reston, VA 20190, USA",
    nearbyStations: ["Wiehle-Reston East", "Reston Town Center"],
    bedrooms: 2,
    bathrooms: 2,
    area: "1200 sqft",
    images: [
      "/images/9_0.jpg",
      "/images/9_1.jpg",
      "/images/9_2.jpg",
      "/images/9_3.jpg",
      "/images/9_4.jpg",
      "/images/9_5.jpg",
      "/images/9_6jpg.webp",
    ],
    IMAGES_FROM:
      "https://www.makersrise.com/PhotoGallery",
  },
  {
    id: 10,
    title: "Luxury Loft in Frankfurt",
    description:
      "Elegant loft apartment located in the heart of Frankfurt, featuring high ceilings, exposed brick walls, and designer furnishings.",
    price: 2000,
    propertyType: "Loft",
    ownerType: "Internal Employee",
    city: "Frankfurt",
    address: "123 Hauptwache, 60313 Frankfurt am Main, Germany",
    nearbyStations: ["Hauptwache", "Konstablerwache"],
    bedrooms: 1,
    bathrooms: 1,
    area: "1000 sqft",
    images: [
      "/images/10_0.jpg",
      "/images/10_1.jpg",
      "/images/10_2.jpg",
      "/images/10_3.jpg",
      "/images/10_4.jpg",
      "/images/10_5.jpg",
      "/images/10_6.jpg",
    ],
    IMAGES_FROM:
      "https://wunderflats.com/en/furnished-apartment/elegant-zeitlos-all-inclusive/63e4befc6c5a9d6a8ff19436?dataLayerKey=atce1MuLZuhngEQtEjAvH&_gl=1*183h01w*_up*MQ..*_ga*ODQ4MDIxOTEwLjE3MTEwNjA5MzQ.*_ga_XQLMYV7TJ8*MTcxMTA2MDkzMi4xLjAuMTcxMTA2MDkzMi4wLjAuMA..",
  },
  {
    id: 11,
    title: "City View Apartment in Hong Kong",
    description:
      "Contemporary apartment offering panoramic views of the Hong Kong skyline, located in the vibrant Central district.",
    price: 2000,
    propertyType: "Apartment",
    ownerType: "Internal Employee",
    city: "Hong Kong",
    address: "123 Queen's Rd Central, Central, Hong Kong",
    nearbyStations: ["Central", "Admiralty"],
    bedrooms: 3,
    bathrooms: 2,
    area: "1800 sqft",
    images: [
      "/images/11_0.jpg",
      "/images/11_1.jpg",
      "/images/11_2.jpg",
      "/images/11_3.jpg",
      "/images/11_4.jpg",
      "/images/11_5.jpg",
      "/images/11_6.jpg",
    ],
    IMAGES_FROM:
      "https://www.booking.com/hotel/vn/hi-home-city-view-apartment-in-hongkong-tower.en-gb.html?aid=356980&label=gog235jc-1DCAso9AFCLWhpLWhvbWUtY2l0eS12aWV3LWFwYXJ0bWVudC1pbi1ob25na29uZy10b3dlckgzWANoRogBAZgBCbgBF8gBDNgBA-gBAYgCAagCA7gCrvLyrwbAAgHSAiQwMTc2NjE5Ni1lYjIyLTRhZDktYmQ3MS0wZjA4MmFhNjAyNWPYAgTgAgE&sid=461f62bc885b914bcd5e172a1142b6f7&dist=0&group_adults=2&keep_landing=1&sb_price_type=total&type=total&",
  },
  {
    id: 12,
    title: "Luxury Condo in Singapore",
    description:
      "Sophisticated condo in the heart of Singapore, offering breathtaking views of the city skyline and premium amenities.",
    price: 2000,
    propertyType: "Condo",
    ownerType: "Internal Employee",
    city: "Singapore",
    address: "123 Orchard Rd, Singapore 238895",
    nearbyStations: ["Orchard", "Somerset"],
    bedrooms: 4,
    bathrooms: 3,
    area: "2200 sqft",
    images: [
      "/images/12_0.jpg",
      "/images/12_1.jpg",
      "/images/12_2.jpg",
      "/images/12_3.jpg",
      "/images/12_4.jpg",
      "/images/12_5.jpg",
      "/images/12_6.jpg",
    ],
    IMAGES_FROM:
      "https://www.example.com/singapore-listing",
  },
  {
    id: 13,
    title: "Harbourfront Penthouse in Sydney",
    description:
      "Luxurious penthouse offering stunning views of Sydney Harbour, with spacious living areas and top-of-the-line amenities.",
    price: 2500,
    propertyType: "Penthouse",
    ownerType: "Internal Employee",
    city: "Sydney",
    address: "123 Circular Quay W, The Rocks NSW 2000, Australia",
    nearbyStations: ["Circular Quay", "Wynyard"],
    bedrooms: 3,
    bathrooms: 3,
    area: "3000 sqft",
    images: [
      "/images/13_0.jpg",
      "/images/13_1.jpg",
      "/images/13_2.jpg",
      "/images/13_3.jpg",
      "/images/13_4.jpg",
      "/images/13_5.jpg",
      "/images/13_6.jpg",
    ],
    IMAGES_FROM:
      "https://www.example.com/sydney-listing",
  },
  {
    id: 14,
    title: "Artistic Loft in Shanghai",
    description:
      "Unique loft space showcasing modern art and design, offering an inspiring environment for creative minds.",
    price: 5500,
    propertyType: "Loft",
    ownerType: "Internal",
    city: "Shanghai",
    address: "123 Huaihai Middle Rd, Huangpu District, Shanghai, China",
    nearbyStations: ["South Huangpi Road", "Xintiandi"],
    bedrooms: 1,
    bathrooms: 1,
    area: "1000 sqft",
    images: [
      "/images/14_0.jpg",
      "/images/14_1.jpg",
      "/images/14_2.jpg",
      "/images/14_3.jpg",
      "/images/14_4.jpg",
      "/images/14_5.jpg",
      "/images/14_6.jpg",
    ],
    IMAGES_FROM:
      "https://www.example.com/shanghai-listing-3",
  },
  {
    id: 15,
    title: "Urban Chic Condo in Toronto",
    description:
      "Stylish condo in the heart of downtown Toronto, featuring contemporary decor and trendy urban living.",
    price: 6000,
    propertyType: "Condo",
    ownerType: "Internal",
    city: "Toronto",
    address: "123 King St W, Toronto, ON M5H 3T9, Canada",
    nearbyStations: ["St. Andrew Station", "Union Station"],
    bedrooms: 2,
    bathrooms: 2,
    area: "1500 sqft",
    images: [
      "/images/15_0.jpg",
      "/images/15_1.jpg",
      "/images/15_2.jpg",
      "/images/15_3.jpg",
      "/images/15_4.jpg",
      "/images/15_5.jpg",
      "/images/15_6.jpg",
    ],
    IMAGES_FROM:
      "https://www.example.com/toronto-listing-3",
  },
  {
    id: 16,
    title: "Tranquil Retreat in Sydney",
    description:
      "Peaceful retreat nestled in the lush greenery of Sydney, offering a serene escape from the city hustle.",
    price: 4500,
    propertyType: "House",
    ownerType: "Internal",
    city: "Sydney",
    address: "123 Ocean Rd, Palm Beach NSW 2108, Australia",
    nearbyStations: ["Wynyard", "Circular Quay"],
    bedrooms: 3,
    bathrooms: 2,
    area: "1800 sqft",
    images: [
      "/images/16_0.jpg",
      "/images/16_1.jpg",
      "/images/16_2.jpg",
      "/images/16_3.jpg",
      "/images/16_4.jpg",
      "/images/16_5.jpg",
      "/images/16_6.jpg",
    ],
    IMAGES_FROM:
      "https://www.example.com/sydney-listing-3",
  },
  {
    id: 17,
    title: "Elegant Condo in Singapore",
    description:
      "Sophisticated condo in the prestigious district of Singapore, offering luxury living with panoramic city views.",
    price: 9000,
    propertyType: "Condo",
    ownerType: "Internal",
    city: "Singapore",
    address: "123 Orchard Blvd, Singapore 248649",
    nearbyStations: ["Orchard MRT Station", "Newton MRT Station"],
    bedrooms: 3,
    bathrooms: 3,
    area: "2000 sqft",
    images: [
      "/images/17_0.jpg",
      "/images/17_1.jpg",
      "/images/17_2.jpg",
      "/images/17_3.jpg",
      "/images/17_4.jpg",
      "/images/17_5.jpg",
      "/images/17_6.jpg",
    ],
    IMAGES_FROM:
      "https://www.example.com/singapore-listing-3",
  },
  {
    id: 18,
    title: "Chic Urban Oasis in Hong Kong",
    description:
      "Chic and stylish apartment serving as an urban oasis in the heart of Hong Kong, offering a serene escape from the city buzz.",
    price: 7500,
    propertyType: "Apartment",
    ownerType: "Internal",
    city: "Hong Kong",
    address: "123 Hollywood Rd, Central, Hong Kong",
    nearbyStations: ["Central Station", "Sheung Wan Station"],
    bedrooms: 2,
    bathrooms: 2,
    area: "1600 sqft",
    images: [
      "/images/18_0.jpg",
      "/images/18_1.jpg",
      "/images/18_2.jpg",
      "/images/18_3.jpg",
      "/images/18_4.jpg",
      "/images/18_5.jpg",
      "/images/18_6.jpg",
    ],
    IMAGES_FROM:
      "https://www.example.com/hongkong-listing-3",
  },
  {
    id: 19,
    title: "Riverfront Condo in Frankfurt",
    description:
      "Luxurious condo with panoramic views of the Main River in Frankfurt, offering exclusive waterfront living.",
    price: 5500,
    propertyType: "Condo",
    ownerType: "Internal",
    city: "Frankfurt",
    address: "123 Untermainkai, 60311 Frankfurt am Main, Germany",
    nearbyStations: ["Willy-Brandt-Platz", "Konstablerwache"],
    bedrooms: 2,
    bathrooms: 2,
    area: "1400 sqft",
    images: [
      "/images/19_0.jpg",
      "/images/19_1.jpg",
      "/images/19_2.jpg",
      "/images/19_3.jpg",
      "/images/19_4.jpg",
      "/images/19_5.jpg",
      "/images/19_6.jpg",
    ],
    IMAGES_FROM:
      "https://www.example.com/frankfurt-listing-3",
  },
];
export default mockListings;
