import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google";
import "./globals.css";

import Header from "../components/Header";
import { cn } from "../lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={cn(
            inter.className,
            "flex min-h-screen flex-col bg-[#d5d3d3]",
          )}
        >
          <Header />
          <main className="self-center">{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
